export const metadata = {
    title: 'Affordable App Development Mumbai | Cross-Platform iOS, Android Apps | UFDev India',
    description:
        'Best app development company in Mumbai, India. Save 40-60% with our affordable cross-platform app development. Get your business app on iOS, Android, and Windows with a single codebase. Local expertise, global standards.',
    keywords: [
        'app development Mumbai',
        'app developer India',
        'affordable app development Mumbai',
        'cheap app developer India',
        'budget app development Mumbai',
        'cross platform app India',
        'react native app development Mumbai',
        'flutter app development India',
        'multi platform app Mumbai',
        'ios android app development India',
        'windows app development Mumbai',
        'business app development India',
        'app for small business Mumbai',
        'cost effective app India',
        'mobile app price Mumbai',
        'app development cost India',
        'app development company Mumbai',
        'build an app cheaply India',
        'create app for business Mumbai',
        'app builder service India',
        'custom app development Mumbai',
        'one codebase multiple platforms',
        'Indian app developers',
        'Mumbai tech company',
        'mobile app agency Maharashtra',
    ],
    alternates: {
        canonical: 'https://ufdev.llc/services/mobile-apps',
    },
    openGraph: {
        title: 'Affordable App Development in Mumbai, India | Cross-Platform Solutions | UFDev',
        description:
            'Top-rated app development company in Mumbai. Build your business app for iOS, Android & Windows at 40-60% less cost. Local expertise with international quality. Get a free quote today!',
        url: 'https://ufdev.llc/services/mobile-apps',
        siteName: 'UFDev',
        images: [
            {
                url: 'https://ufdev.llc/images/og/mobile-apps.jpg',
                width: 1200,
                height: 630,
                alt: 'Affordable App Development in Mumbai by UFDev India',
            }
        ],
        locale: 'en_IN',
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: 'Best App Development Company in Mumbai | Save 40-60% | UFDev India',
        description: 'Leading mobile app developer in Mumbai, India. Get your app on iOS, Android & Windows for less than you would pay for a single platform. Local support, global standards.',
        images: ['https://ufdev.llc/images/twitter/mobile-apps.jpg'],
        creator: '@ufdev_llc',
    },
    robots: {
        index: true,
        follow: true,
        nocache: true,
        googleBot: {
            index: true,
            follow: true,
            'max-image-preview': 'large',
            'max-snippet': -1,
        },
    },
    category: 'Mobile App Development Services India',
    publishedTime: '2024-05-22T10:00:00Z',
    tags: ['App Development Mumbai', 'App Development India', 'Cross-Platform', 'React Native', 'Flutter', 'iOS', 'Android', 'Windows', 'Mobile Apps', 'Affordable Development', 'Maharashtra'],
}; 